version: '3'

tasks:
  build:
    cmds:
      - tsc -p ./tsconfig.json --module es2015 --outDir ./lib/esm && tsc -p ./tsconfig.json --module commonjs --outDir ./lib
      - cp ./LICENSE ./lib/LICENSE
      - cp ./README.md ./lib/README.md
      - cp ./package.json ./lib/package.json
      - touch ./package-temp.json
      - jq '.types = "./esm/index.d.ts"' ./lib/package.json > ./package-temp.json
      - mv ./package-temp.json ./lib/package.json
  publish:
    cmd: npm publish ./lib --access public